language: python
python:
  - 2.7

sudo: required
dist: trusty

notifications:
  email: 
    - daas@physik.uni-bonn.de

before_install:
  - sudo add-apt-repository -y ppa:team-electronics/ppa
  - sudo apt-get update

install:
  - sudo apt-get install -qq iverilog-daily
  
  - pip install bitarray pyyaml nose zmq tables
  
  - git clone https://github.com/potentialventures/cocotb.git
  - export COCOTB=$(pwd)/cocotb
  
  - git clone -b development https://github.com/SiLab-Bonn/basil; cd basil; python setup.py develop; cd ..;

script:
  - cd tests;  nosetests test_*.py